version: '3.7'
services:
    service1:
        build:
            context: ./service1
            dockerfile: Dockerfile
        image: wasimd/service1
        ports:
        - target: 5000
          published: 5000
          protocol: tcp
        environment:
          DATABASE_URI: mysql+pymysql://root:1234@34.105.173.206/Destination
    service2:
        build:
            context: ./service2
            dockerfile: Dockerfile
        image: wasimd/service2
        ports:
        - target: 5001
          published: 5001
          protocol: tcp
    service3:
        build:
            context: ./service3
            dockerfile: Dockerfile
        image: wasimd/service3
        ports:
        - target: 5002
          published: 5002 
          protocol: tcp
    service4:
        build:
            context: ./service4
            dockerfile: Dockerfile
        image: wasimd/service4
        ports:
        - target: 5003
          published: 5003
          protocol: tcp