- name: install pip
  apt:
    name: python3-pip

- name: install docker with pip
  pip:
    name: docker

- name: Start Swarm
  docker_swarm:
    state: present

- name: Inspect swarm
  docker_swarm:
    state: inspect
  register: swarm_info