- name: install pip
  apt:
    name: python3-pip

- name: Install docker with pip
  pip:
    name: docker

- name: Add first node
  docker_swarm:
    state: join
    advertise_addr: worker
    join_token: "SWMTKN-1-05clcjm074kj48wvfmsfn6qvg8adl7tijbh0p0roa23kis11kx-a066j5iqv0empscni6x03se7t"
    remote_addrs: sfia2:2377

- name: Add second node
  docker_swarm:
    state: join
    advertise_addr: workertwo
    join_token: "SWMTKN-1-05clcjm074kj48wvfmsfn6qvg8adl7tijbh0p0roa23kis11kx-a066j5iqv0empscni6x03se7t"
    remote_addrs: sfia2:2377