- name: install pip
  apt:
    name: python3-pip

- name: Install docker with pip
  pip:
    name: docker

- name: Add node
  shell: docker swarm join --token {{ hostvars['token']['value'] }} {{ hostvars['managerhostname']['value'] }}:2377
  ignore_errors: true    
