- name: install pip
  apt:
    name: python3-pip

- name: Install docker with pip
  pip:
    name: docker

- name: Add node
  docker_swarm:
    state: join
    advertise_addr: worker
    join_token: "SWMTKN-1-4q2g9ju6hu33yw52ij60y5gf8ycb6jqgizmqz8hanpkpkgwt9l-4xgx1qy8uka4ze1m3u0qce65l"
    remote_addrs: sfia2:2377
