- name: install pip
  apt:
    name: python3-pip

- name: Install docker with pip
  pip:
    name: docker

- name: Add first node
  docker_swarm:
    state: join
    advertise_addr: worker
    join_token: "SWMTKN-1-4d1ajomorytdm0utp4suk4kc9gh2yxdqsjlv9jq2k3unj6cz52-9im1knp92moptnqidp3yylz8b"
    remote_addrs: sfia2:2377

- name: Add second node
  docker_swarm:
    state: join
    advertise_addr: workertwo
    join_token: "SWMTKN-1-4d1ajomorytdm0utp4suk4kc9gh2yxdqsjlv9jq2k3unj6cz52-9im1knp92moptnqidp3yylz8b"
    remote_addrs: sfia2:2377