- name: apt update and package installs
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    state: latest
    update_cache: true

- name: GPG Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present


- name: Docker Repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable"
    state: present

- name: Install Docker
  apt:
    pkg:
    - docker-ce 
    - docker-ce-cli
    - containerd.io
    state: latest
    update_cache: true

- name: Docker Group
  group:
    name: "docker"
    state: present

- name: Adding user
  user:
    name: "jenkins"
    groups: "docker"
    append: "yes"